[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

sourceSets {
  main {
    resources {
      srcDir 'src/main/java'
      include '**/*.json'
    }
  }
}

dependencies {
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.github.raeleus.TenPatch:tenpatch:$tenPatchVersion"

  api "com.github.pizpizi:pvz-skin:v0.1.1"
  implementation 'com.github.pizpizi:libPVZ:v0.1.6'

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.register('runServer', JavaExec) {
  group = 'application'
  description = 'Run the Phase 3 PvZ server-client backend.'
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'network.server.PvZServer'
  standardInput = System.in
}
