package models.engine.events;

public enum GameEventType {
    WAVE_STARTED,
    ZOMBIE_SPAWNED,
    ZOMBIE_KILLED,
    PLANT_DESTROYED,
    LAWN_MOWER_TRIGGERED,
    PLANT_SUN_PRODUCED,
    SKY_SUN_DROPPING,
    SKY_SUN_LANDED,
    RADIOACTIVE_SUN_EXPLODED,
    PLANT_FOOD_DROPPED,
    REWARD_DROPPED,
    CHAPTER_EFFECT
}
